name: Angular-GettingStarted CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: '13.x'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - name: Publish build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
      - name: Publish code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage
      - name: Replace SF directories in coverage/lcov.info
        run: sed -i 's+/home/runner/work/Angular-GettingStarted/Angular-GettingStarted+/github/workspace+g' coverage/lcov.info
      - name: SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: SonarSource/sonarcloud-github-action@v1.3

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist
      - name: Install firebase
        run: sudo npm install -g firebase-tools
      - name: Deploy to Firebase
        run: firebase deploy --public . --project angular-getting-started-apm --only hosting
        working-directory: dist/apm
